clear; clc;

mdl = 'SPM_GA';
STOP_TIME = '20000';

lb = 1.5;
ub = 9.0;

opts = optimoptions('ga', ...
    'PopulationSize', 12, ...
    'MaxGenerations', 15, ...
    'Display', 'iter', ...
    'UseParallel', false);

[x_opt, fval] = ga( ...
    @(x) ga_objective(x, mdl, STOP_TIME), ...
    1, [], [], [], [], ...
    lb, ub, [], ...
    opts);

fprintf('\n=============================\n');
fprintf('Optimal charging current = %.3f A\n', x_opt);
fprintf('Objective value (time+penalty) = %.1f\n', fval);
fprintf('=============================\n');
